ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_origins = []
ticket_server_cors_allow_methods = "All"
ticket_server_cors_allow_credentials = true
ticket_server_cors_max_age = 300

data_server_enabled = false

name = "umccr-htsget-rs"
version = "0.1"
organization_name = "UMCCR"
organization_url = "https://umccr.org/"
contact_url = "https://umccr.org/"
documentation_url = "https://github.com/umccr/htsget-rs"
environment = "dev"

# C4GH prefix indicates Crypt4GH files.
[[resolvers]]
regex = '^(?P<bucket>.*?)/(?P<key>c4gh/.*)$'
substitution_string = '$key'
storage.backend = 'S3'

[resolvers.storage.keys]
location = "SecretsManager"
private_key = "htsget-rs/c4gh-private-key-c4gh" # pragma: allowlist secret
recipient_public_key = "htsget-rs/c4gh-recipient-public-key-c4gh"

# Everything else is a regular file.
[[resolvers]]
regex = '^(?P<bucket>.*?)/(?P<key>c4gh/.*)$'
substitution_string = '$key'
storage.backend = 'S3'

[resolvers.storage.keys]
location = "SecretsManager"
private_key = "htsget-rs/c4gh-private-key-c4gh" # pragma: allowlist secret
recipient_public_key = "htsget-rs/c4gh-recipient-public-key-c4gh"

# Everything else is a regular file.
[[resolvers]]
regex = '^(?P<bucket>.*?)/(?P<key>c4gh/.*)$'
substitution_string = '$key'
storage.backend = 'S3'

[resolvers.storage.keys]
location = "SecretsManager"
private_key = "htsget-rs/c4gh-private-key-c4gh" # pragma: allowlist secret
recipient_public_key = "htsget-rs/c4gh-recipient-public-key-c4gh"

# Everything else is a regular file.
[[resolvers]]
regex = '^(?P<bucket>.*?)/(?P<key>.*)$'
substitution_string = '$key'
storage.backend = 'S3'
