ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_origins = [
    "https://data.umccr.org",
    "https://data.prod.umccr.org",
    "https://portal.prod.umccr.org",
    "https://portal.umccr.org"
]
ticket_server_cors_allow_methods = "All"
ticket_server_cors_allow_credentials = true
ticket_server_cors_max_age = 300

data_server_enabled = false

name = "umccr-htsget-rs"
version = "0.1"
organization_name = "UMCCR"
organization_url = "https://umccr.org/"
contact_url = "https://umccr.org/"
documentation_url = "https://github.com/umccr/htsget-rs"
environment = "prod"

[[resolvers]]
regex = '^(umccr-research-dev)/(?P<key>.*)$'
substitution_string = '$key'
storage.backend = 'S3'

[[resolvers]]
regex = '^(umccr-validation-prod)/(?P<key>.*)$'
substitution_string = '$key'
storage.backend = 'S3'

[[resolvers]]
regex = '^(umccr-primary-data-prod)/(?P<key>.*)$'
substitution_string = '$key'
storage.backend = 'S3'
