version: "3"

services:
  htsget-rs:
    image: ghcr.io/umccr/htsget-rs:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Change this to any data location to serve files using default settings.
      - ./../../../data:/data
