data_server_enabled = false

[[resolvers]]
regex = '.*'
substitution_string = '$0'

[resolvers.storage]
bucket = 'data'
# The minio endpoint is set as the minio service within docker compose.
endpoint = 'http://minio:9000'
# Optionally, force path style addressing.
#path_style = true
