name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - uses: cloudflare/wrangler-actions@v3
        with:
          command: wrangler types
          workingDirectory: cloudflare
      - run: pnpm install
      - run: pnpm run build
